{{- if not .Values.secrets.existingRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft-whitelist.secretRef" . }}
  labels:
    {{- include "minecraft-whitelist.labels" . | nindent 4 }}
stringData:
  APP_KEY: {{ .Values.secrets.appKey | quote }}

  MAIL_DRIVER: {{ .Values.secrets.mail.driver | quote }}
  MAIL_HOST: {{ .Values.secrets.mail.host | quote }}
  MAIL_PORT: {{ .Values.secrets.mail.port | quote }}
  MAIL_USERNAME: {{ .Values.secrets.mail.username | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mail.password | quote }}
  MAIL_ENCRYPTION: {{ .Values.secrets.mail.encryption | quote }}
  MAIL_FROM: {{ .Values.secrets.mail.from | quote }}

  DB_HOST: {{ .Values.secrets.db.host | quote }}
  DB_PORT: {{ .Values.secrets.db.port | quote }}
  DB_USERNAME: {{ .Values.secrets.db.username | quote }}
  DB_PASSWORD: {{ .Values.secrets.db.password | quote }}
  DB_DATABASE: {{ .Values.secrets.db.database | quote }}
  DB_PREFIX: {{ .Values.secrets.db.prefix | quote }}
{{- end}}
