version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    DB_HOST: "database"
    DB_PORT: "3306"
    DB_DATABASE: "panel"
    DB_USERNAME: "pterodactyl"
    DB_PASSWORD: &db-password "CHANGE_ME"
  panel:
    &panel-environment
    APP_KEY: "CHANGE_ME"
    APP_URL: "https://control.essiebes.nl"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "Europe/Amsterdam"
    APP_SERVICE_AUTHOR: "noreply@essiebes.nl"
    LOG_CHANNEL: "stderr"
    TRUSTED_PROXIES: "*"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@essiebes.nl"
    MAIL_DRIVER: "log"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  cache:
    image: redis:alpine:latest
    restart: always
    ports:
      - "6379:6379"
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - cache
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
