apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-cache'
  labels:
    katenary.io/component: cache
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: b7f5aea89ff7ce93065ab68374c8a58d03a35cf5
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: cache
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: cache
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: cache
          image: '{{ .Values.cache.repository.image }}{{ if ne .Values.cache.repository.tag "" }}:{{ .Values.cache.repository.tag }}{{ end }}'
          ports:
            - name: cache
              containerPort: 6379

