apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-panel'
  labels:
    katenary.io/component: panel
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: b7f5aea89ff7ce93065ab68374c8a58d03a35cf5
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: panel
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: panel
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: panel
          image: '{{ .Values.panel.repository.image }}{{ if ne .Values.panel.repository.tag "" }}:{{ .Values.panel.repository.tag }}{{ end }}'
          ports:
            - name: panel
              containerPort: 80
            - name: panel-443
              containerPort: 443
          env:
            - name: QUEUE_DRIVER
              value: '{{ tpl .Values.panel.environment.QUEUE_DRIVER . }}'
            - name: SESSION_DRIVER
              value: '{{ tpl .Values.panel.environment.SESSION_DRIVER . }}'
            - name: DB_PASSWORD
              value: '{{ tpl .Values.panel.environment.DB_PASSWORD . }}'
            - name: APP_TIMEZONE
              value: '{{ tpl .Values.panel.environment.APP_TIMEZONE . }}'
            - name: CACHE_DRIVER
              value: '{{ tpl .Values.panel.environment.CACHE_DRIVER . }}'
            - name: MAIL_USERNAME
              value: '{{ tpl .Values.panel.environment.MAIL_USERNAME . }}'
            - name: TRUSTED_PROXIES
              value: '{{ tpl .Values.panel.environment.TRUSTED_PROXIES . }}'
            - name: MAIL_PORT
              value: '{{ tpl .Values.panel.environment.MAIL_PORT . }}'
            - name: REDIS_HOST
              value: '{{ tpl .Values.panel.environment.REDIS_HOST . }}'
            - name: MAIL_ENCRYPTION
              value: '{{ tpl .Values.panel.environment.MAIL_ENCRYPTION . }}'
            - name: APP_ENVIRONMENT_ONLY
              value: '{{ tpl .Values.panel.environment.APP_ENVIRONMENT_ONLY . }}'
            - name: MAIL_PASSWORD
              value: '{{ tpl .Values.panel.environment.MAIL_PASSWORD . }}'
            - name: MAIL_HOST
              value: '{{ tpl .Values.panel.environment.MAIL_HOST . }}'
            - name: APP_URL
              value: '{{ tpl .Values.panel.environment.APP_URL . }}'
            - name: MAIL_FROM
              value: '{{ tpl .Values.panel.environment.MAIL_FROM . }}'
            - name: LOG_CHANNEL
              value: '{{ tpl .Values.panel.environment.LOG_CHANNEL . }}'
            - name: APP_ENV
              value: '{{ tpl .Values.panel.environment.APP_ENV . }}'
            - name: APP_KEY
              value: '{{ tpl .Values.panel.environment.APP_KEY . }}'
            - name: APP_SERVICE_AUTHOR
              value: '{{ tpl .Values.panel.environment.APP_SERVICE_AUTHOR . }}'
            - name: MAIL_DRIVER
              value: '{{ tpl .Values.panel.environment.MAIL_DRIVER . }}'

