{{- if .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "essies-xbackbone.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "essies-xbackbone.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
    {{- with .Values.networkPolicy }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}