apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "essies-xbackbone.labels" . | nindent 4 }}
  name: {{ include "essies-xbackbone.fullname" . }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "essies-xbackbone.selectorLabels" . | nindent 4 }}
  type: ClusterIP