apiVersion: v1
kind: Service
metadata:
  name: {{ include "essies-toys.fullname" . }}-deepstream
  labels:
    {{- include "essies-toys.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deepstream.service.type }}
  ports:
    - port: {{ .Values.deepstream.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "essies-toys.selectorLabels.deepstream" . | nindent 4 }}
