{{- if .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "essies-toys.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "essies-toys.selectorLabels.shared" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "essies-toys.selectorLabels.socketio" . | nindent 12 }}
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
      - podSelector:
          matchLabels:
            {{- include "essies-toys.selectorLabels.api" . | nindent 12 }}
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
    {{- with .Values.networkPolicy }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}