apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "essies-toys.fullname" . }}-socketio
  labels:
    {{- include "essies-toys.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.socketio.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "essies-toys.selectorLabels.socketio" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.socketio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "essies-toys.selectorLabels.socketio" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "essies-toys.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.socketio.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.socketio.securityContext | nindent 12 }}
          image: "{{ .Values.socketio.image.repository }}:{{ .Values.socketio.image.tag }}"
          imagePullPolicy: {{ .Values.socketio.image.pullPolicy }}
          ports:
            - name: ws
              containerPort: {{ .Values.socketio.service.port }}
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: ws
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: ws
          readinessProbe:
            tcpSocket:
              port: ws
          resources:
            {{- toYaml .Values.socketio.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "essies-toys.fullname" . }}-socketio-config
      {{- with .Values.socketio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.socketio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.socketio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
