version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
#      - BASE_URL=https://changedetection
    volumes:
      - config:/config
    ports:
      - 5000:5000
    restart: unless-stopped
volumes:
  config:
    external: true
