# Default values for portfolio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterDomain: cluster.local
revisionHistoryLimit: 3
probesEnabled: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: essiebes/kube
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80
  internalPort: ""

resources: {}

config:
  existingRef: ""
    
  environment: production
  debug: false
  appUrl: "http://panel.example.com"
  appTimezone: "UTC"

  logChannel: "stderr"
  trustedProxies: "*"

secrets:
  existingRef: ""
  
  appKey: ""

  mail:
    driver: "log"
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
    encryption: ""

  db:
    host: "mysql"
    port: 3306
    username: pterodactyl
    password: ""
    database: "panel"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
