{{- if not .Values.config.existingRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pterodactyl.configMapRef" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.panel.environment | quote }}
  APP_DEBUG: {{ .Values.config.panel.debug | quote }}
  APP_URL: {{ .Values.config.panel.appUrl | quote }}
  APP_TIMEZONE: {{ .Values.config.panel.appTimezone | quote }}
  APP_SERVICE_AUTHOR: {{ .Values.config.panel.serviceAuthor | quote }}
  APP_CLEAR_TASKLOG: {{ .Values.config.panel.clearTaskLog | quote }}
  APP_DELETE_MINUTES: {{ .Values.config.panel.deleteMinutes | quote }}
  PTERODACTYL_FILES_MAX_EDIT_SIZE: "5000000"
  APP_ENVIRONMENT_ONLY: "false"
  APP_LOCALE: "en"

  QUEUE_HIGH: "high"
  QUEUE_STANDARD: "standard"
  QUEUE_LOW: "low"

  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"

  SESSION_SECURE_COOKIE: "true"
{{- end}}
