{{- if not .Values.secrets.existingRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.secretRef" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
stringData:
  APP_KEY: {{ .Values.secrets.panel.appKey }}

  MAIL_DRIVER: {{ .Values.secrets.mail.driver }}
  MAIL_HOST: {{ .Values.secrets.mail.host }}
  MAIL_PORT: {{ .Values.secrets.mail.port | toString }}
  MAIL_USERNAME: {{ .Values.secrets.mail.username }}
  MAIL_PASSWORD: {{ .Values.secrets.mail.password }}
  MAIL_ENCRYPTION: {{ .Values.secrets.mail.encryption | toString }}
  MAIL_FROM: {{ .Values.secrets.mail.from }}
{{- end}}
