apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "essies-changedetection-io.labels" . | nindent 4 }}
  name: {{ include "essies-changedetection-io.fullname" . }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 5000
      targetPort: http
  selector:
    {{- include "essies-changedetection-io.selectorLabels" . | nindent 4 }}
  type: ClusterIP
status:
  loadBalancer: {}
