apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: changedetection
  name: changedetection
spec:
  clusterIP: None
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: changedetection
  type: ClusterIP
status:
  loadBalancer: {}
